### ISSUE TITLE
test_midas.py -vf  test_class (__main__._07_RunSNPs) ... FAIL

### ISSUE THREAD

**Issue by qiileee** [snayfach/MIDAS#111]
Hi,
While I run the test_midas.py, the runSNPs always fail, I had no idea about it.
The error was reported as follows：
FAIL: test_class (__main__._07_RunSNPs)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/lisi/ZW/software/MIDAS/test/test_midas.py", line 102, in test_class
    self.assertTrue(code==0, msg=err)
AssertionError: Traceback (most recent call last):
  File "/media/lisi/ZW/software/MIDAS/scripts/run_midas.py", line 757, in <module>
    run_program(program, args)
  File "/media/lisi/ZW/software/MIDAS/scripts/run_midas.py", line 82, in run_program
    snps.run_pipeline(args)
  File "/media/lisi/ZW/software/MIDAS/midas/run/snps.py", line 301, in run_pipeline
    pysam_pileup(args, species, contigs)
  File "/media/lisi/ZW/software/MIDAS/midas/run/snps.py", line 228, in pysam_pileup
    aln_stats = utility.parallel(species_pileup, argument_list, args['threads'])
  File "/media/lisi/ZW/software/MIDAS/midas/utility.py", line 101, in parallel
    return [r.get() for r in results]
  File "/media/lisi/ZW/software/miniconda2/envs/lisi/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
AttributeError: 'pysam.calignmentfile.AlignmentFile' object has no attribute 'count_coverage'

Maybe there is something wrong with my installed pysam, but the version of my pysam is 0.8.1 according to the guideline of installation manual of MIDAS. , I would appreciate it if somebody can give me some advice on this issue.

**Comment by qiileee** [comment]
I'm so sorry for my disturbance, I have solved this problem by upgrading my pysam.
