### ISSUE TITLE
test not completing sucessfully

### ISSUE THREAD

**Issue by sanpande** [snayfach/MIDAS#115]
I get following error. Any suggestions ?
>./test_midas.py -vf
test_class (__main__._01_CheckEnv) ... ok
test_class (__main__._02_ImportDependencies) ... ok
test_class (__main__._03_CheckVersions) ... ok
test_class (__main__._04_HelpText) ... ok
test_class (__main__._05_RunSpecies) ... ok
test_class (__main__._06_RunGenes) ... ok
test_class (__main__._07_RunSNPs) ... FAIL

======================================================================
FAIL: test_class (__main__._07_RunSNPs)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test_midas.py", line 102, in test_class
    self.assertTrue(code==0, msg=err)
AssertionError: False is not true : b'Traceback (most recent call last):\n  File "...anaconda3/envs/midas/bin/run_midas.py", line 757, in <module>\n    run_program(program, args)\n  File "...anaconda3/envs/midas/bin/run_midas.py", line 82, in run_program\n    snps.run_pipeline(args)\n  File "...../MIDAS/MIDAS/midas/run/snps.py", line 301, in run_pipeline\n    pysam_pileup(args, species, contigs)\n  File "...../MIDAS/MIDAS/midas/run/snps.py", line 228, in pysam_pileup\n    aln_stats = utility.parallel(species_pileup, argument_list, args[\'threads\'])\n  File "...../MIDAS/MIDAS/midas/utility.py", line 101, in parallel\n    return [r.get() for r in results]\n  File "...../MIDAS/MIDAS/midas/utility.py", line 101, in <listcomp>\n    return [r.get() for r in results]\n  File "...anaconda3/envs/midas/lib/python3.7/multiprocessing/pool.py", line 657, in get\n    raise self._value\n  File "...anaconda3/envs/midas/lib/python3.7/multiprocessing/pool.py", line 431, in _handle_tasks\n    put(task)\n  File "...anaconda3/envs/midas/lib/python3.7/multiprocessing/connection.py", line 206, in send\n    self._send_bytes(_ForkingPickler.dumps(obj))\n  File "...anaconda3/envs/midas/lib/python3.7/multiprocessing/reduction.py", line 51, in dumps\n    cls(buf, protocol).dump(obj)\nTypeError: cannot serialize \'_io.TextIOWrapper\' object\n'
----------------------------------------------------------------------
Ran 7 tests in 28.075s

FAILED (failures=1)

**Comment by sanpande** [comment]
older version of python (v2.7) fixed it.
