### ISSUE TITLE
test_midas.py fail for test 7

### ISSUE THREAD

**Issue by linzhouzz** [snayfach/MIDAS#117]
Hi, when I ran test_midas.py, I received an error message for the RunSNPs test. Do you potentially know what is causing this?

======================================================================
FAIL: test_class (__main__._07_RunSNPs)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_midas.py", line 102, in test_class
    self.assertTrue(code==0, msg=err)
AssertionError: Traceback (most recent call last):
  File "/u/local/apps/midas/1.3.2/MIDAS/scripts/run_midas.py", line 757, in <module>
    run_program(program, args)
  File "/u/local/apps/midas/1.3.2/MIDAS/scripts/run_midas.py", line 82, in run_program
    snps.run_pipeline(args)
  File "/u/local/apps/midas/1.3.2/MIDAS/midas/run/snps.py", line 301, in run_pipeline
    pysam_pileup(args, species, contigs)
  File "/u/local/apps/midas/1.3.2/MIDAS/midas/run/snps.py", line 228, in pysam_pileup
    aln_stats = utility.parallel(species_pileup, argument_list, args['threads'])
  File "/u/local/apps/midas/1.3.2/MIDAS/midas/utility.py", line 101, in parallel
    return [r.get() for r in results]
  File "/u/local/apps/anaconda2/2019.10/envs/midas/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
AttributeError: 'pysam.calignmentfile.AlignmentFile' object has no attribute 'count_coverage'

**Comment by tbazilegith** [comment]
Hi also have issues with python test_midas.py -vf. Could anyone have an idea about this?
test_class (__main__._01_CheckEnv) ... ok
test_class (__main__._02_ImportDependencies) ... ok
test_class (__main__._03_CheckVersions) ... ok
test_class (__main__._04_HelpText) ... ok
test_class (__main__._05_RunSpecies) ... FAIL

======================================================================
FAIL: test_class (__main__._05_RunSpecies)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_midas.py", line 90, in test_class
    self.assertTrue(code==0, msg=err)
AssertionError: False is not true : b'\nError: could not execute samtools binary: /blue/bphl-username/directory/MIDAS/bin/Linux/samtools\n(exited with error code 1)\nTo solve this issue, follow these steps:\n  1) Download samtools v1.4: https://github.com/samtools/samtools/releases/download/1.4/samtools-1.4.tar.bz2\n  2) Unpack and compile the software on your system\n  3) Copy the new samtools binary to: sername/directory/MIDAS/bin/Linux\n\n'

When I download and unpack samtools-1.4.tar.bz2, the samtools binary is unseen.
