### ISSUE TITLE
Building  database error

### ISSUE THREAD

**Issue by JX-Zhong** [snayfach/MIDAS#119]
Hi, When I want to build a 30 species pangenome database for snp calling, I meet some errors.  fna and other files were downloaded from PATRIC database. I found that some of strain's fna files failed for building , but I have not found any difference between these files. Error is 
`
Building pangenome database
Finegoldia_magna
  catting genes
  clustering genes
Traceback (most recent call last):
  File "/home/zhongjiaxin/app/MIDAS/scripts/build_midas_db.py", line 74, in <module>
    build_db.run_pipeline(args)
  File "/home/zhongjiaxin/app/MIDAS/midas/build/build_db.py", line 490, in run_pipeline
    build_pangenome_db(args, species)
  File "/home/zhongjiaxin/app/MIDAS/midas/build/build_db.py", line 323, in build_pangenome_db
    p.cluster_genes(args['threads'], args['resume'])
  File "/home/zhongjiaxin/app/MIDAS/midas/build/build_db.py", line 151, in cluster_genes
    self.store_cluster_membership()
  File "/home/zhongjiaxin/app/MIDAS/midas/build/build_db.py", line 170, in store_cluster_membership
    gene.centroid_99 = gene.centroid_id[99]
KeyError: 99

`

**Comment by JX-Zhong** [comment]
[Finegoldia_magna_FDAARGOS_764.zip](https://github.com/snayfach/MIDAS/files/6814488/Finegoldia_magna_FDAARGOS_764.zip)

**Comment by JX-Zhong** [comment]
I meet another error when I try to use merge_midas.py , error output is
`Traceback (most recent call last):
  File "/home/shileisheng/anaconda3/envs/py2.7/bin/merge_midas.py", line 441, in <module>
    run_program(program, args)
  File "/home/shileisheng/anaconda3/envs/py2.7/bin/merge_midas.py", line 431, in run_program
    snps.run_pipeline(args)
  File "/home/zhongjiaxin/app/MIDAS/midas/merge/snps.py", line 499, in run_pipeline
    parallel_build_sharded_tables(species, args)
  File "/home/zhongjiaxin/app/MIDAS/midas/merge/snps.py", line 387, in parallel_build_sharded_tables
    parallel(build_sharded_tables, argument_list, args['threads'])
  File "/home/zhongjiaxin/app/MIDAS/midas/merge/snps.py", line 225, in parallel
    r.get()
  File "/home/shileisheng/anaconda3/envs/py2.7/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
KeyError: 'end'
`
how to sovlve it ?

**Comment by JX-Zhong** [comment]
I meet another error when I try to use merge_midas.py , error output is
Traceback (most recent call last): File "/home/shileisheng/anaconda3/envs/py2.7/bin/merge_midas.py", line 441,
 in <module> run_program(program, args) 
File "/home/shileisheng/anaconda3/envs/py2.7/bin/merge_midas.py", line 431, in run_program snps.run_pipeline(args) File "/home/zhongjiaxin/app/MIDAS/midas/merge/snps.py", line 499, 
in run_pipeline parallel_build_sharded_tables(species, args) 
File "/home/zhongjiaxin/app/MIDAS/midas/merge/snps.py", line 387,
 in parallel_build_sharded_tables parallel(build_sharded_tables, argument_list, args['threads']) 
File "/home/zhongjiaxin/app/MIDAS/midas/merge/snps.py", line 225, in parallel r.get() File "/home/shileisheng/anaconda3/envs/py2.7/lib/python2.7/multiprocessing/pool.py", line 572,
 in get raise self._value 
KeyError: 'end'
how to sovlve it ?

**Comment by Damianyangyang** [comment]
Hi~May I ask how you downloaded the reference genome, how did you download the .gene file and the .faa file?
