### ISSUE TITLE
test_class (__main__._07_RunSNPs) ... FAIL

### ISSUE THREAD

**Issue by Daisyiscool** [snayfach/MIDAS#130]
Hello,

I'm very new to MIDAS and also Linux. Can you please help me with this error?
When I run `test_midas.py -vf`, RunSNPs always fail. What's the problem here? 

FAIL: test_class (__main__._07_RunSNPs)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/daisy/MIDAS/test/test_midas.py", line 102, in test_class
    self.assertTrue(code==0, msg=err)
AssertionError: False is not true : b'Traceback (most recent call last):\n  File "/home/daisy/MIDAS/scripts/run_midas.py", line 757, in <module>\n    run_program(program, args)\n  File "/home/daisy/MIDAS/scripts/run_midas.py", line 82, in run_program\n    snps.run_pipeline(args)\n  File "/home/daisy/MIDAS/midas/run/snps.py", line 301, in run_pipeline\n    pysam_pileup(args, species, contigs)\n  File "/home/daisy/MIDAS/midas/run/snps.py", line 228, in pysam_pileup\n    aln_stats = utility.parallel(species_pileup, argument_list, args[\'threads\'])\n  File "/home/daisy/MIDAS/midas/utility.py", line 101, in parallel\n    return [r.get() for r in results]\n  File "/home/daisy/MIDAS/midas/utility.py", line 101, in <listcomp>\n    return [r.get() for r in results]\n  File "/home/daisy/anaconda3/lib/python3.9/multiprocessing/pool.py", line 771, in get\n    raise self._value\n  File "/home/daisy/anaconda3/lib/python3.9/multiprocessing/pool.py", line 537, in _handle_tasks\n    put(task)\n  File "/home/daisy/anaconda3/lib/python3.9/multiprocessing/connection.py", line 211, in send\n    self._send_bytes(_ForkingPickler.dumps(obj))\n  File "/home/daisy/anaconda3/lib/python3.9/multiprocessing/reduction.py", line 51, in dumps\n    cls(buf, protocol).dump(obj)\nTypeError: cannot pickle \'_io.TextIOWrapper\' object\n'

Thank you.

Daisy

**Comment by Arch0nnn** [comment]
@Daisyiscool Hello, when I run python test.py -vf, it stops and displays test_class (__main__._07_RunSNPs)... FAIL. The reason for the error is the same as what you mentioned. How did you solve it? Thank you very much for your reply
