### ISSUE TITLE
Tests fails at MergeGenes (merge_midas.py genes)

### ISSUE THREAD

**Issue by mherold1** [snayfach/MIDAS#35]
Hello,

similarly to https://github.com/snayfach/MIDAS/issues/20 running `test_midas.py` fails at this step: 
```
./test_midas.py 
....F.....
======================================================================
FAIL: test_help_text (__main__.MergeGenes)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test_midas.py", line 132, in test_help_text
    self.assertTrue(sum(self.retcodes)==0, msg=error)
AssertionError: 

Failed to execute the command: merge_midas.py genes 

----------------------------------------------------------------------
Ran 10 tests in 252.652s

FAILED (failures=1)
```

I am running MIDAS on python 2.7.3

I traced back the error a bit and it probably comes from this call `merge_midas.py genes ./genes -i ./sample -t list --species_id Bacteroides_vulgatus_57955 --sample_depth 0.0`, when I run it separately it shows the following error message:

```
[...]
Identifying species
  found 1 species with sufficient high-coverage samples

Merging: Bacteroides_vulgatus_57955 for 1 samples
Traceback (most recent call last):
  File "/work/local_tools/MIDAS/scripts/merge_midas.py", line 352, in <module>
    run_program(program, args)
  File "/work/local_tools/MIDAS/scripts/merge_midas.py", line 339, in run_program
    merge_genes.run_pipeline(args)
  File "/work/local_tools/MIDAS/midas/merge/merge_genes.py", line 109, in run_pipeline
    read_cluster_map(sp, args['db'], args['cluster_pid'])
  File "/work/local_tools/MIDAS/midas/merge/merge_genes.py", line 97, in read_cluster_map
    sp.map[r['centroid_99']] =  r['centroid_%s' % pid]
KeyError: 'centroid_95'
```

Do you know why this happens?

**Comment by snayfach** [comment]
Could you send me the version of the software and database? They should
both be v1.2.

**Comment by mherold1** [comment]
I was using db 1.1, I will retry after updating

**Comment by mherold1** [comment]
Updating to v1.2 fixed the problem
