### ISSUE TITLE
Help with genes error: libchtslib 

### ISSUE THREAD

**Issue by elhwashington** [snayfach/MIDAS#73]
Hello,
   I have been trying to get MIDAS, installed by a former lab member, to run. So far I think that I have run_midas.py species running but when I then try run_midas.py genes on the samples I just ran through species I receive the following error
Traceback (most recent call last):
  File "/Users/mcleanlab/Tools/MIDAS/scripts/run_midas.py", line 757, in <module>
    run_program(program, args)
  File "/Users/mcleanlab/Tools/MIDAS/scripts/run_midas.py", line 79, in run_program
    genes.run_pipeline(args)
  File "/Users/mcleanlab/Tools/MIDAS/midas/run/genes.py", line 286, in run_pipeline
    pangenome_coverage(args, species, genes)
  File "/Users/mcleanlab/Tools/MIDAS/midas/run/genes.py", line 149, in pangenome_coverage
    count_mapped_bp(args, species, genes)
  File "/Users/mcleanlab/Tools/MIDAS/midas/run/genes.py", line 173, in count_mapped_bp
    import pysam
  File "/Users/mcleanlab/Downloads/pysam-master/pysam/__init__.py", line 5, in <module>
    from pysam.libchtslib import *
ImportError: No module named libchtslib
I have looked for libchtslib and found libchtslib.pxd, libchstlib.c and libchtslib.o deep inside the pysam-master folder.  However, even adding the corresponding folders to the python path did not correct the issue. 
I  am looking for help.  Hopefully I'm just confused and the answer is simple.

thank you for your time
Erik Hendrickson

**Comment by elhwashington** [comment]
Thank you for the help. 
Sadly, I am on a legacy system and re-installing something is pretty much out. Fortunately, I have gotten the Docker version to run.
Again, thank you for the reply

Erik Hendrickson

**Comment by snayfach** [comment]
In that case I'm closing this issue, but feel free to reopen as necessary.

Thanks,
Stephen

**Comment by nick-youngblut** [comment]
At least on some linux systems, the midas bioconda recipe is installing pysam=0.15.4, which when imported generates the `ImportError: No module named libchtslib` error. Specifying`pysam>=0.16` in the midas bioconda recipe should help to avoid the issue
