### ISSUE TITLE
Running in Python 2 conda environment works for all `species` and `genes` but not `snps`. 

### ISSUE THREAD

**Issue by jolespin** [snayfach/MIDAS#79]
I'm trying to run the `MIDAS` pipeline using a Python 2 environment configured for use with `MIDAS`.  My main environment is a `Python 3.6` environment and it looks like the correct Python version is being called in my Python 2 environment but one stage is calling `multiprocessing` from `Python 3.6`.

**Do you know if there are any patches I can do to bypass this and call the correct `multiprocessing` module?** 

```
(python2) -bash-4.1$ cat snps_18.e8829501
Traceback (most recent call last):
  File "/usr/local/devel/ANNOTATION/jespinoz/anaconda/envs/python2/lib/python2.7/site-packages/MIDAS/scripts/run_midas.py", line 757, in <module>
    run_program(program, args)
  File "/usr/local/devel/ANNOTATION/jespinoz/anaconda/envs/python2/lib/python2.7/site-packages/MIDAS/scripts/run_midas.py", line 82, in run_program
    snps.run_pipeline(args)
  File "/usr/local/devel/ANNOTATION/jespinoz/anaconda/envs/python2/lib/python2.7/site-packages/MIDAS/midas/run/snps.py", line 301, in run_pipeline
    pysam_pileup(args, species, contigs)
  File "/usr/local/devel/ANNOTATION/jespinoz/anaconda/envs/python2/lib/python2.7/site-packages/MIDAS/midas/run/snps.py", line 228, in pysam_pileup
    aln_stats = utility.parallel(species_pileup, argument_list, args['threads'])
  File "/usr/local/devel/ANNOTATION/jespinoz/anaconda/envs/python2/lib/python2.7/site-packages/MIDAS/midas/utility.py", line 101, in parallel
    return [r.get() for r in results]
  File "/usr/local/devel/ANNOTATION/jespinoz/anaconda/envs/python2/lib/python2.7/site-packages/MIDAS/midas/utility.py", line 101, in <listcomp>
    return [r.get() for r in results]
  File "/usr/local/devel/ANNOTATION/jespinoz/anaconda/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/usr/local/devel/ANNOTATION/jespinoz/anaconda/lib/python3.6/multiprocessing/pool.py", line 424, in _handle_tasks
    put(task)
  File "/usr/local/devel/ANNOTATION/jespinoz/anaconda/lib/python3.6/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/usr/local/devel/ANNOTATION/jespinoz/anaconda/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: cannot serialize '_io.TextIOWrapper' object
```

**Comment by snayfach** [comment]
Hey Josh,

Thanks for posting the error, but I'm not really sure of the solution. In the past I tested successfully with python 3. Were you able to get the unit test to run to completion? Sorry I can't be of more help.

Stephen

**Comment by jolespin** [comment]
I wonder if it's the way I installed this?  I've gotten it to work before so I'm pretty confused.  Do you know what script may be calling my default Python 3.6 multiprocessing?

**Comment by bsiranosian** [comment]
Hi, I had a similar error when installing via anaconda (but python 3). I fixed it by changing the pysam_pileup part of the snps pipeline to run in a single core. This works for the example dataset at least. 

in snps.py:
```
def pysam_pileup(args, species, contigs):
...
	# disable parallel processing for this step
	# aln_stats = utility.parallel(species_pileup, argument_list, args['threads'])
	aln_stats = [species_pileup(args[0], args[1], args[2]) for args in argument_list]
...
```

**Comment by GRvdPloeg** [comment]
I've had a similar issue trying to develop a metagenomics analysis pipeline involving MIDAS on a computing environment with the correct packages installed. This was done by following the tutorial documentation and using a python 3.6.8 installation.

I can provide more details if required. Let me know if I can help!

**Comment by Aiswarya-prasad** [comment]
You can still use multithreading if you simply add an extra line to the function pysam_pileup(). The issue seems to be the passing of the file handler for the log file. You could simple remove that with `del args['log']`. I am not sure if this has other unintended consequences. But so far it seems to work for me.
