### ISSUE TITLE
RunSpecies fail during test

### ISSUE THREAD

**Issue by ilevade** [snayfach/MIDAS#85]
Hi ! I'm trying to install MIDAS and I encountered several error messages due to problems with the dependencies and the version of samtools and bowtie2, I fixed them, but I have this new error message that I couldn't undertand: 

test_class (__main__._01_CheckEnv) ... ok
test_class (__main__._02_ImportDependencies) ... ok
test_class (__main__._03_CheckVersions) ... ok
test_class (__main__._04_HelpText) ... ok
test_class (__main__._05_RunSpecies) ... FAIL

======================================================================
FAIL: test_class (__main__._05_RunSpecies)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ilevade/MIDAS/scripts/test_midas.py", line 90, in test_class
    self.assertTrue(code==0, msg=err)
AssertionError: Traceback (most recent call last):
  File "/home/ilevade/MIDAS/scripts/run_midas.py", line 752, in <module>
    check_arguments(program, args)
  File "/home/ilevade/MIDAS/scripts/run_midas.py", line 51, in check_arguments
    check_species(args)
  File "/home/ilevade/MIDAS/scripts/run_midas.py", line 172, in check_species
    if args['m1']: args['file_type'] = utility.auto_detect_file_type(args['m1'])
  File "/home/ilevade/MIDAS/midas/utility.py", line 154, in auto_detect_file_type
    infile = iopen(inpath)
  File "/home/ilevade/MIDAS/midas/utility.py", line 199, in iopen
    if ext == 'gz': return gzip.open(inpath, mode)
  File "/home/linuxbrew/.linuxbrew/Cellar/python@2/2.7.14_4/lib/python2.7/gzip.py", line 34, in open
    return GzipFile(filename, mode, compresslevel)
  File "/home/linuxbrew/.linuxbrew/Cellar/python@2/2.7.14_4/lib/python2.7/gzip.py", line 94, in __init__
    fileobj = self.myfileobj = __builtin__.open(filename, mode or 'rb')
IOError: [Errno 2] No such file or directory: './test.fq.gz'

----------------------------------------------------------------------
Ran 5 tests in 2.542s

FAILED (failures=1)

Thank you in advance for the help !

**Comment by snayfach** [comment]
It looks like the script cant find the test.fq.gz file which is located
under MIDAS/test. Make sure that the file exists and you're running the
script from the MIDAS/test directory

**Comment by qiileee** [comment]
Hello, I have the same error with you now. How did you solve it?
