### ISSUE TITLE
test_midas.py -vf  test_class (__main__._07_RunSNPs) ... FAIL

### ISSUE THREAD

**Issue by biofuture** [snayfach/MIDAS#89]
While I run  the rest_midas.py, the runSNPs always fail, what is the problem?  Can not identify it. 

./test_midas.py -vf
test_class (__main__._01_CheckEnv) ... ok
test_class (__main__._02_ImportDependencies) ... /srv/scratch/z3524677/bin/miniconda3/lib/python3.6/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)
/srv/scratch/z3524677/bin/miniconda3/lib/python3.6/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)
ok
test_class (__main__._03_CheckVersions) ... ok
test_class (__main__._04_HelpText) ... ok
test_class (__main__._05_RunSpecies) ... ok
test_class (__main__._06_RunGenes) ... ok
test_class (__main__._07_RunSNPs) ... FAIL

======================================================================
FAIL: test_class (__main__._07_RunSNPs)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test_midas.py", line 102, in test_class
    self.assertTrue(code==0, msg=err)
AssertionError: False is not true : b'Traceback (most recent call last):\n  File "/srv/scratch/z3524677/bin/MIDAS/scripts/run_midas.py", line 757, in <module>\n    run_program(program, args)\n  File "/srv/scratch/z3524677/bin/MIDAS/scripts/run_midas.py", line 82, in run_program\n    snps.run_pipeline(args)\n  File "/srv/scratch/z3524677/bin/MIDAS/midas/run/snps.py", line 301, in run_pipeline\n    pysam_pileup(args, species, contigs)\n  File "/srv/scratch/z3524677/bin/MIDAS/midas/run/snps.py", line 228, in pysam_pileup\n    aln_stats = utility.parallel(species_pileup, argument_list, args[\'threads\'])\n  File "/srv/scratch/z3524677/bin/MIDAS/midas/utility.py", line 101, in parallel\n    return [r.get() for r in results]\n  File "/srv/scratch/z3524677/bin/MIDAS/midas/utility.py", line 101, in <listcomp>\n    return [r.get() for r in results]\n  File "/srv/scratch/z3524677/bin/miniconda3/lib/python3.6/multiprocessing/pool.py", line 644, in get\n    raise self._value\n  File "/srv/scratch/z3524677/bin/miniconda3/lib/python3.6/multiprocessing/pool.py", line 424, in _handle_tasks\n    put(task)\n  File "/srv/scratch/z3524677/bin/miniconda3/lib/python3.6/multiprocessing/connection.py", line 206, in send\n    self._send_bytes(_ForkingPickler.dumps(obj))\n  File "/srv/scratch/z3524677/bin/miniconda3/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps\n    cls(buf, protocol).dump(obj)\nTypeError: cannot serialize \'_io.TextIOWrapper\' object\n'

----------------------------------------------------------------------
Ran 7 tests in 57.474s

FAILED (failures=1)

**Comment by snayfach** [comment]
Can you try running with python2 instead of python3?

**Comment by biofuture** [comment]
After transfer to python 2.7.3 it works.

**Comment by biofuture** [comment]
Thanks

**Comment by michaelwasney** [comment]
Hello,

I am having this same issue. I initially tried running it on Python 3.6, and got the error detail by the original poster.

I then tried doing the installation process using python 2.7, as suggested. However, I then ran when trying to install dependencies (i.e., before even getting to the installation step):

```
(python27_env) [michaelw@n6005 test]$ pip install -U numpy biopython pysam pandas
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Requirement already up-to-date: numpy in /u/home/m/michaelw/.conda/envs/python27_env/lib/python2.7/site-packages (1.16.6)
Collecting biopython
  Downloading https://files.pythonhosted.org/packages/3d/2f/d9df24de05d651c5e686ee8fea3afe3985c03ef9ca02f4cc1e7ea10aa31e/biopython-1.77.tar.gz (16.8MB)
     |████████████████████████████████| 16.8MB 281kB/s 
    ERROR: Command errored out with exit status 1:
     command: /u/home/m/michaelw/.conda/envs/python27_env/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/work/tmp/pip-install-Bp1mz9/biopython/setup.py'"'"'; __file__='"'"'/work/tmp/pip-install-Bp1mz9/biopython/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /work/tmp/pip-install-Bp1mz9/biopython/pip-egg-info
         cwd: /work/tmp/pip-install-Bp1mz9/biopython/
    Complete output (1 lines):
    Biopython requires Python 3.6 or later. Python 2.7 detected.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
(python27_env) [michaelw@n6005 test]$ conda deactivate
[michaelw@n6005 test]$ pip install -U numpy biopython pysam pandas
Could not fetch URL https://pypi.python.org/simple/numpy/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:618) - skipping
Requirement already up-to-date: numpy in /usr/lib64/python2.7/site-packages
Cache entry deserialization failed, entry ignored
Collecting biopython
  Downloading https://files.pythonhosted.org/packages/9e/7f/eaca4de03f0ee06c9d578d2730fd55858a57cee3620c62d3bc17b5da5447/biopython-1.84.tar.gz (25.8MB)
    100% |████████████████████████████████| 25.8MB 34kB/s 
    Complete output from command python setup.py egg_info:
    ERROR: Biopython requires Python 3.9 or later. Python 2.7 detected.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /work/tmp/pip-build-LMAiS2/biopython/
```

It seems like installing dependencies (specifically, biopython) doesn't work with python 2, but testing MIDAS doesn't work with python 3. Can you advise on a workaround for this?

**Comment by Arch0nnn** [comment]
@biofuture @snayfach This situation still occurs after I set the python environment to 2.7. The following error message is reported:
======================================================================
FAIL: test_class (__main__._07_RunSNPs)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_midas.py", line 102, in test_class
    self.assertTrue(code==0, msg=err)
AssertionError: Traceback (most recent call last):
  File "/home/bioinfo/huangyx/SNV_MIDAS/MIDAS/scripts/run_midas.py", line 757, in <module>
    run_program(program, args)
  File "/home/bioinfo/huangyx/SNV_MIDAS/MIDAS/scripts/run_midas.py", line 82, in run_program
    snps.run_pipeline(args)
  File "/home/bioinfo/huangyx/SNV_MIDAS/MIDAS/midas/run/snps.py", line 301, in run_pipeline
    pysam_pileup(args, species, contigs)
  File "/home/bioinfo/huangyx/SNV_MIDAS/MIDAS/midas/run/snps.py", line 228, in pysam_pileup
    aln_stats = utility.parallel(species_pileup, argument_list, args['threads'])
  File "/home/bioinfo/huangyx/SNV_MIDAS/MIDAS/midas/utility.py", line 101, in parallel
    return [r.get() for r in results]
  File "/home/bioinfo/huangyx/.conda/envs/midas/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
AttributeError: 'pysam.calignmentfile.AlignmentFile' object has no attribute 'count_coverage'


----------------------------------------------------------------------
